---
- name: Download filebeat {{ filebeat_version }}
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-{{ filebeat_version }}-x86_64.rpm
    dest: /opt/
    mode: '0440'

- name: Install Filebeat
  command: rpm -vi /opt/filebeat-oss-{{ filebeat_version }}-x86_64.rpm

- name: Enable module system
  command: filebeat modules enable system
  ignore_errors: True


